local dap = require("dap")
local ui = require("dapui")

Keymap("n", "<leader>dd", function()
	ui.toggle()
end, { desc = "Toggle DAP UI" })
Keymap("n", "<leader>dB", function()
	dap.set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, { desc = "Breakpoint Condition" })
Keymap("n", "<leader>db", function()
	dap.toggle_breakpoint()
end, { desc = "Toggle Breakpoint" })
Keymap("n", "<leader>dc", function()
	dap.continue()
end, { desc = "Run/Continue" })
Keymap("n", "<leader>dC", function()
	dap.run_to_cursor()
end, { desc = "Run to Cursor" })
Keymap("n", "<leader>dg", function()
	dap.goto_()
end, { desc = "Go to Line (No Execute)" })
Keymap("n", "<leader>di", function()
	dap.step_into()
end, { desc = "Step Into" })
Keymap("n", "<leader>dj", function()
	dap.down()
end, { desc = "Down" })
Keymap("n", "<leader>dk", function()
	dap.up()
end, { desc = "Up" })
Keymap("n", "<leader>dl", function()
	dap.run_last()
end, { desc = "Run Last" })
Keymap("n", "<leader>do", function()
	dap.step_out()
end, { desc = "Step Out" })
Keymap("n", "<leader>dO", function()
	dap.step_over()
end, { desc = "Step Over" })
Keymap("n", "<leader>dP", function()
	dap.pause()
end, { desc = "Pause" })
Keymap("n", "<leader>dr", function()
	dap.repl.toggle()
end, { desc = "Toggle REPL" })
Keymap("n", "<leader>ds", function()
	dap.session()
end, { desc = "Session" })
Keymap("n", "<leader>dt", function()
	dap.terminate()
end, { desc = "Terminate" })
Keymap("n", "<leader>dw", function()
	require("dap.ui.widgets").hover()
end, { desc = "Widgets" })
